#!/usr/bin/env bash
#
# worktree.sh — create a git worktree wired up for parallel local dev.
#
# Built on top of `git worktree`. It:
#   1. adds a worktree (+ branch) named <name> as a sibling of the repo,
#   2. copies every .env* file into it, adding <offset> to every dev *PORT= line,
#   3. writes apps/debug/.env.local and apps/dashboard/.env.local so those apps
#      listen on their own ports and proxy to this worktree's server port.
#
# Usage:
#   scripts/worktree.sh <name> [offset]
#
#   name    branch + directory name for the new worktree
#   offset  integer added to every dev port (default: 10 * existing worktrees,
#           so the first extra worktree gets 10, the next 20, ...)
#
# Base ports: debug 3000, dashboard 4000, server = PORT in apps/server/.env
# (3001). With offset 10 the worktree runs debug on 3010, dashboard on 4010,
# and server on 3011.
set -euo pipefail

usage() { echo "usage: ${0##*/} <name> [offset]" >&2; exit 1; }

NAME="${1:-}"
[ -n "$NAME" ] || usage
OFFSET="${2:-}"

ROOT="$(git rev-parse --show-toplevel)"
DEST="$(dirname "$ROOT")/$NAME"

DEBUG_BASE=3000
DASHBOARD_BASE=4000
SERVER_BASE="$(grep -E '^[[:space:]]*PORT=' "$ROOT/apps/server/.env" 2>/dev/null \
  | tail -1 | sed -E 's/.*=[[:space:]]*//' | tr -dc '0-9')"
SERVER_BASE="${SERVER_BASE:-3001}"

# Default offset: 10 per existing worktree (the main tree counts as one).
if [ -z "$OFFSET" ]; then
  count="$(git worktree list --porcelain | grep -c '^worktree ')"
  OFFSET=$(( count * 10 ))
fi
case "$OFFSET" in *[!0-9]*) echo "offset must be a non-negative integer" >&2; exit 1;; esac

DEBUG_PORT=$(( DEBUG_BASE + OFFSET ))
DASHBOARD_PORT=$(( DASHBOARD_BASE + OFFSET ))
SERVER_PORT=$(( SERVER_BASE + OFFSET ))

echo "Creating worktree '$NAME' at $DEST (offset $OFFSET)"
echo "  debug     -> http://localhost:$DEBUG_PORT"
echo "  dashboard -> http://localhost:$DASHBOARD_PORT"
echo "  server    -> http://localhost:$SERVER_PORT"

# Add the worktree, reusing the branch if it already exists.
if git show-ref --quiet "refs/heads/$NAME"; then
  git worktree add "$DEST" "$NAME"
else
  git worktree add -b "$NAME" "$DEST"
fi

# Copy every .env* file (skipping *.example), offsetting only *PORT= lines so
# real ports inside DATABASE_URL etc. are left untouched.
cd "$ROOT"
while IFS= read -r -d '' f; do
  rel="${f#./}"
  dst="$DEST/$rel"
  mkdir -p "$(dirname "$dst")"
  OFFSET="$OFFSET" perl -pe \
    's/^(\s*(?:export\s+)?(?:[A-Z0-9]+_)*PORT\s*=\s*)(\d+)/$1 . ($2 + $ENV{OFFSET})/e' \
    "$f" > "$dst"
  echo "  copied $rel"
done < <(find . -type f \( -name '.env' -o -name '.env.*' \) \
  ! -name '*.example' -not -path '*/node_modules/*' -print0)

# Point the debug and dashboard apps at this worktree's ports. Each app's
# next.config.js reads SERVER_URL from here, and its dev script reads PORT.
debug_env="$DEST/apps/debug/.env.local"
mkdir -p "$(dirname "$debug_env")"
{
  echo "# Generated by scripts/worktree.sh (offset $OFFSET)"
  echo "PORT=$DEBUG_PORT"
  echo "SERVER_URL=http://localhost:$SERVER_PORT"
} > "$debug_env"
echo "  wrote apps/debug/.env.local"

dashboard_env="$DEST/apps/dashboard/.env.local"
mkdir -p "$(dirname "$dashboard_env")"
{
  echo "# Generated by scripts/worktree.sh (offset $OFFSET)"
  echo "PORT=$DASHBOARD_PORT"
  echo "SERVER_URL=http://localhost:$SERVER_PORT"
} > "$dashboard_env"
echo "  wrote apps/dashboard/.env.local"

echo
echo "Done. Next:"
echo "  cd $DEST && pnpm install && pnpm dev"
