#!/usr/bin/env bash
#
# worktree.sh — create a git worktree wired up for parallel local dev.
#
# Built on top of `git worktree`. It:
#   1. adds a worktree (+ branch) named <name> as a sibling of the repo,
#   2. copies every .env* file into it, adding <offset> to every dev *PORT= line,
#   3. writes apps/debug/.env.local, apps/dashboard/.env.local,
#      apps/backend/.env.local and apps/homepage/.env.local so those apps listen
#      on their own ports (debug/dashboard/backend also point at this worktree's
#      browser-server and auth-server ports).
#
# Usage:
#   scripts/worktree.sh <name> [offset]
#
#   name    branch + directory name for the new worktree
#   offset  integer added to every dev port (default: 10 * existing worktrees,
#           so the first extra worktree gets 10, the next 20, ...)
#
# Base ports: debug 3000, browser-server = PORT in apps/browser-server/.env
# (3001), backend 3002, homepage 3050, dashboard 4000. With offset 10 the
# worktree runs debug on 3010, browser-server on 3011, backend on 3012,
# homepage on 3060, and dashboard on 4010.
set -euo pipefail

usage() { echo "usage: ${0##*/} <name> [offset]" >&2; exit 1; }

NAME="${1:-}"
[ -n "$NAME" ] || usage
OFFSET="${2:-}"

ROOT="$(git rev-parse --show-toplevel)"
DEST="$(dirname "$ROOT")/$NAME"

DEBUG_BASE=3000
DASHBOARD_BASE=4000
BROWSER_SERVER_BASE="$(grep -E '^[[:space:]]*PORT=' "$ROOT/apps/browser-server/.env" 2>/dev/null \
  | tail -1 | sed -E 's/.*=[[:space:]]*//' | tr -dc '0-9')"
BROWSER_SERVER_BASE="${BROWSER_SERVER_BASE:-3001}"
BACKEND_BASE=3002
HOMEPAGE_BASE=3050

# Default offset: 10 per existing worktree (the main tree counts as one).
if [ -z "$OFFSET" ]; then
  count="$(git worktree list --porcelain | grep -c '^worktree ')"
  OFFSET=$(( count * 10 ))
fi
case "$OFFSET" in *[!0-9]*) echo "offset must be a non-negative integer" >&2; exit 1;; esac

DEBUG_PORT=$(( DEBUG_BASE + OFFSET ))
DASHBOARD_PORT=$(( DASHBOARD_BASE + OFFSET ))
BROWSER_SERVER_PORT=$(( BROWSER_SERVER_BASE + OFFSET ))
BACKEND_PORT=$(( BACKEND_BASE + OFFSET ))
HOMEPAGE_PORT=$(( HOMEPAGE_BASE + OFFSET ))

# The ports never collide within a single worktree (distinct bases, same
# offset). The real risk is a NEW worktree's port landing on one already taken by
# another running tree — e.g. offset 50 puts debug on 3050, another tree's
# homepage base. Warn (don't fail) if any target port is already bound so we don't
# silently create a worktree whose app can't start.
if command -v lsof >/dev/null 2>&1; then
  for p in "$DEBUG_PORT" "$DASHBOARD_PORT" "$BROWSER_SERVER_PORT" "$BACKEND_PORT" "$HOMEPAGE_PORT"; do
    if lsof -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then
      echo "warning: port $p is already in use — the worktree's app may fail to bind." >&2
    fi
  done
fi

echo "Creating worktree '$NAME' at $DEST (offset $OFFSET)"
echo "  debug          -> http://localhost:$DEBUG_PORT"
echo "  dashboard      -> http://localhost:$DASHBOARD_PORT"
echo "  homepage       -> http://localhost:$HOMEPAGE_PORT"
echo "  browser-server -> http://localhost:$BROWSER_SERVER_PORT"
echo "  backend        -> http://localhost:$BACKEND_PORT"

# Add the worktree, reusing the branch if it already exists.
if git show-ref --quiet "refs/heads/$NAME"; then
  git worktree add "$DEST" "$NAME"
else
  git worktree add -b "$NAME" "$DEST"
fi

# Copy every .env* file (skipping *.example), offsetting only *PORT= lines so
# real ports inside DATABASE_URL etc. are left untouched.
cd "$ROOT"
while IFS= read -r -d '' f; do
  rel="${f#./}"
  dst="$DEST/$rel"
  mkdir -p "$(dirname "$dst")"
  OFFSET="$OFFSET" perl -pe \
    's/^(\s*(?:export\s+)?(?:[A-Z0-9]+_)*PORT\s*=\s*)(\d+)/$1 . ($2 + $ENV{OFFSET})/e' \
    "$f" > "$dst"
  echo "  copied $rel"
done < <(find . -type f \( -name '.env' -o -name '.env.*' \) \
  ! -name '*.example' -not -path '*/node_modules/*' -print0)

# Point the debug app at this worktree's ports. Its next.config.js reads
# BROWSER_SERVER_URL from here, and its dev script reads PORT.
debug_env="$DEST/apps/debug/.env.local"
mkdir -p "$(dirname "$debug_env")"
{
  echo "# Generated by scripts/worktree.sh (offset $OFFSET)"
  echo "PORT=$DEBUG_PORT"
  echo "BROWSER_SERVER_URL=http://localhost:$BROWSER_SERVER_PORT"
} > "$debug_env"
echo "  wrote apps/debug/.env.local"

# The dashboard's secrets (DATABASE_URL, BETTER_AUTH_SECRET,
# API_TOKEN_ENCRYPTION_KEY, RESEND_*) live in .env.local, copied above. Strip the
# keys we offset, then re-append them so the secrets are preserved and the
# dashboard's self-URL + port match this worktree.
dashboard_env="$DEST/apps/dashboard/.env.local"
mkdir -p "$(dirname "$dashboard_env")"
if [ -f "$dashboard_env" ]; then
  kept="$(grep -vE '^[[:space:]]*(PORT|BETTER_AUTH_URL)[[:space:]]*=' "$dashboard_env" || true)"
else
  kept=""
fi
{
  [ -n "$kept" ] && printf '%s\n' "$kept"
  echo ""
  echo "# Generated by scripts/worktree.sh (offset $OFFSET)"
  echo "PORT=$DASHBOARD_PORT"
  echo "BETTER_AUTH_URL=http://localhost:$DASHBOARD_PORT"
} > "$dashboard_env"
echo "  wrote apps/dashboard/.env.local"

# Point the backend at this worktree's browser server + auth server. Its secrets
# (DATABASE_URL, API_TOKEN_ENCRYPTION_KEY, BROWSER_SERVER_BYPASS_TOKEN) come from
# the copied .env; these overrides live in .env.local (loaded with precedence).
backend_env="$DEST/apps/backend/.env.local"
mkdir -p "$(dirname "$backend_env")"
{
  echo "# Generated by scripts/worktree.sh (offset $OFFSET)"
  echo "PORT=$BACKEND_PORT"
  echo "BROWSER_SERVER_URL=http://localhost:$BROWSER_SERVER_PORT"
  echo "BROWSER_SERVER_PUBLIC_URL=http://localhost:$BROWSER_SERVER_PORT"
  echo "AUTH_SERVER_URL=http://localhost:$DASHBOARD_PORT"
} > "$backend_env"
echo "  wrote apps/backend/.env.local"

# Point the homepage app at this worktree's port. Its dev/start scripts read PORT
# from .env.local (defaulting to 3050). Homepage is a static marketing page, so it
# needs no browser-server URL.
homepage_env="$DEST/apps/homepage/.env.local"
mkdir -p "$(dirname "$homepage_env")"
{
  echo "# Generated by scripts/worktree.sh (offset $OFFSET)"
  echo "PORT=$HOMEPAGE_PORT"
} > "$homepage_env"
echo "  wrote apps/homepage/.env.local"

echo
echo "Done. Next:"
echo "  cd $DEST && pnpm install && pnpm dev"
